### PR TITLE
Self signed certs

### PR DESCRIPTION
**Pull request by iamemilio**
@rudolphpienaar @danmcp 
- Requires the new verison of pfurl, and the previous pr to pfurl
- Can now communicate with pman/pfioh over https 
   - in order to do this all you have to do is change the address to start with https://
- Introduced a new field in the services tree, 'trusted':  [ True  |  False ]
   - setting this to true will allow pfcon to make insecure connections that accept self signed certificates

### CODE REVIEW

**Comment by danmcp** [comment]
@iamemilio Please squash the commits

**Comment by iamemilio** [comment]
changing the syntax to --insecure and squashing

**Comment by iamemilio** [comment]
fixed

**Comment by iamemilio** [comment]
fixed

**Pull request merged**
