### PR TITLE
Refactor/streamline

### PR DESCRIPTION
**Pull request by rudolphpienaar**
Trim down the large config/global var to bare essentials.
Add ability to set/get from global config via external REST calls.
Add CLI to read config from file system.

### CODE REVIEW

**Comment by rudolphpienaar** [comment]
Hi all --

Some of the commit history reflects my attempts to rebase after undoing the changes from last week. This PR simplifies the internal pfcon lookup table/var, and also adds the ability to get/set "compute resource" values with pfurl calls.

Testing with local builds of the whole system had successful integration tests.

Also, looks like the Travis tests triggered by this PR also worked -- i.e. e2e passed.

@danmcp @ravisantoshgudimetla @iamemilio

**Comment by rudolphpienaar** [comment]
@iamemilio  -- if ok with @danmcp  and @ravisantoshgudimetla for this PR, I'd suggest to use this as the base for your changes to pfurl.

**Comment by danmcp** [comment]
@rudolphpienaar Can you squash the commits?

**Comment by rudolphpienaar** [comment]
Sure... how do I do that? :-)

**Comment by rudolphpienaar** [comment]
Is it enough to just select "squash and merge" from the drop down?

**Comment by rudolphpienaar** [comment]
* Remove extra config.json

**Pull request merged**
